# Generated by Django 5.1.6 on 2026-01-25 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especialidade', models.CharField(choices=[('Cardiologista', 'Cardiologista'), ('Medicina Geral', 'Medicina Geral'), ('Radiologista', 'Radiologista'), ('Pediatria', 'Pediatria')], max_length=30)),
                ('n_ordem', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('telefone', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='medico/')),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('dataN', models.DateField()),
                ('telefone', models.IntegerField()),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('tipoConsulta', models.CharField(choices=[('Cardiologia', 'Cardiologia'), ('Consulta Geral', 'Consulta Geral'), ('Radiologia', 'Radiologia'), ('Pediatria', 'Pediatria')], max_length=30)),
                ('status', models.CharField(choices=[('PENDENTE', 'PENDENTE'), ('REALIZADA', 'REALIZADA'), ('CANCELADA', 'CANCELADA')], default='PENDENTE', max_length=30)),
                ('motivo_consulta', models.TextField(blank=True, null=True)),
                ('queixa_principal', models.TextField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exames', models.JSONField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANALISE', 'Em Análise'), ('FINALIZADO', 'Finalizado')], default='PENDENTE', max_length=20)),
                ('realizado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_analise', to='usuarios.consulta')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento_Doze', models.CharField(max_length=100)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescricoes', to='usuarios.consulta')),
            ],
        ),
    ]
